/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx}', './lib/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#13121b',
        'surface-dim': '#13121b',
        'surface-bright': '#3a3842',
        'surface-container-lowest': '#0e0d16',
        'surface-container-low': '#1c1b23',
        'surface-container': '#201f27',
        'surface-container-high': '#2a2932',
        'surface-container-highest': '#35343d',
        'on-surface': '#e5e0ed',
        'on-surface-variant': '#c8c4d7',
        'inverse-surface': '#e5e0ed',
        'inverse-on-surface': '#312f39',
        outline: '#928ea0',
        'outline-variant': '#474555',
        'surface-tint': '#c6bfff',
        primary: '#c6bfff',
        'on-primary': '#29009f',
        'primary-container': '#8d7fff',
        'on-primary-container': '#23008d',
        'inverse-primary': '#5844d9',
        secondary: '#f6bd56',
        'on-secondary': '#422c00',
        'secondary-container': '#976900',
        'on-secondary-container': '#fff7f0',
        tertiary: '#ffb876',
        'on-tertiary': '#4b2800',
        'tertiary-container': '#d27c18',
        'on-tertiary-container': '#422200',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#13121b',
        'on-background': '#e5e0ed',
        'surface-variant': '#35343d',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        card: '0.875rem',
      },
      maxWidth: { container: '1440px' },
    },
  },
  plugins: [],
};
